name: Github Actions

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  tests:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node.version }}
      - name: Install
        run: ng build
      - name: Test
        run: ng test
       
